import {useEffect,useState} from 'react';
type Request=<T>(path:string,body?:unknown,method?:string)=>Promise<T>;
type Settings={kind:string;memoryMB:number;cpuMillis:number;mountPath:string;volumeName:string;network:string;startCommand?:string;preDeployCommand?:string;preDeployTimeoutSeconds?:number;restartPolicy?:string;restartMaxRetries?:number};
type Service={id:string;name:string;projectId:string;environment:string;host:string;activeId:string;settings:Settings;desiredState:string;resourceKind?:string;template?:string;templateVersion?:string;workloadMode?:string};
type Backup={id:string;serviceId:string;size:number;createdAt:string};
export function OperationsPanel({service,services,request,refresh,pending}:{service:Service;services:Service[];request:Request;refresh:()=>Promise<unknown>;pending:boolean}){
 const [memory,setMemory]=useState(service.settings.memoryMB);const [cpu,setCPU]=useState(service.settings.cpuMillis/1000);const [mount,setMount]=useState(service.settings.mountPath);const [host,setHost]=useState(service.host);const [startCommand,setStartCommand]=useState(service.settings.startCommand||'');const [preDeployCommand,setPreDeployCommand]=useState(service.settings.preDeployCommand||'');const [preDeployTimeout,setPreDeployTimeout]=useState(service.settings.preDeployTimeoutSeconds||300);const [restartPolicy,setRestartPolicy]=useState(service.settings.restartPolicy||'on-failure');const [restartRetries,setRestartRetries]=useState(service.settings.restartMaxRetries||10);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const [metrics,setMetrics]=useState<{memoryBytes?:number;cpuPercent?:number|null;status?:string}>({});const [backups,setBackups]=useState<Backup[]>([]);const [restore,setRestore]=useState('');const [confirm,setConfirm]=useState(false);const [target,setTarget]=useState('');const [variable,setVariable]=useState(service.template==='redis'?'REDIS_URL':service.template==='mysql'?'MYSQL_URL':service.template==='mongo'?'MONGO_URL':'DATABASE_URL');
 const database=service.resourceKind==='database'||['postgres','redis','mysql','mongo'].includes(service.settings.kind);const postgres=service.template==='postgres'||service.settings.kind==='postgres';const mysql=service.template==='mysql'||service.settings.kind==='mysql';const mongo=service.template==='mongo'||service.settings.kind==='mongo';const onlineBackup=postgres||mysql||mongo;const volumeActionReady=onlineBackup?service.desiredState!=='stopped':service.desiredState==='stopped';
 useEffect(()=>{let done=false;const load=async()=>{try{const [m,b]=await Promise.all([request<typeof metrics>(`/api/services/${service.id}/metrics`),request<Backup[]>('/api/backups')]);if(!done){setMetrics(m);setBackups(b)}}catch(e){if(!done)setError((e as Error).message)}};void load();const timer=setInterval(load,5000);return()=>{done=true;clearInterval(timer)}},[service.id,request]);
 const perform=async(work:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');setNotice('');try{await work();await refresh();setNotice(message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <div className="deployment-content operations-panel"><h3>Observed usage</h3><div className="usage-grid"><div><span>Memory</span><strong>{metrics.memoryBytes==null?'—':(metrics.memoryBytes/1048576).toFixed(1)+' MB'}</strong></div><div><span>CPU</span><strong>{metrics.cpuPercent==null?'—':metrics.cpuPercent.toFixed(1)+'%'}</strong></div><div><span>Runtime</span><strong>{metrics.status||'Unknown'}</strong></div></div>
 <h3>Resource limits & storage</h3><p className="muted">Changes apply to the next deployment. Persistent services pause briefly while replacing their container.</p><form onSubmit={e=>{e.preventDefault();void perform(()=>request(`/api/services/${service.id}/settings`,{memoryMB:memory,cpuMillis:Math.round(cpu*1000),mountPath:mount},'PUT'),'Settings saved. Deploy again to apply.')}}><div className="form-row"><div><label htmlFor="memory-limit">Memory limit (MB)</label><input id="memory-limit" type="number" min={mysql||mongo?512:postgres?256:64} max={4096} value={memory} onChange={e=>setMemory(Number(e.target.value))}/></div><div><label htmlFor="cpu-limit">CPU limit</label><input id="cpu-limit" type="number" min={.1} max={4} step={.1} value={cpu} onChange={e=>setCPU(Number(e.target.value))}/></div></div><label htmlFor="volume-path">Persistent volume path</label><input id="volume-path" placeholder="/data (optional)" value={mount} disabled={!!service.settings.mountPath} onChange={e=>setMount(e.target.value)}/>{service.settings.volumeName&&<p className="field-help">This volume is retained across deployments and service stops.</p>}<button className="secondary spaced-label" disabled={busy}>Save resource settings</button></form>
 {!database&&<><h3 className="spaced-label">Deploy commands & recovery</h3><p className="muted">Commands run through <code>/bin/sh</code> inside the image. Pre-deploy runs once in a separate container without the service volume.</p><form onSubmit={e=>{e.preventDefault();void perform(()=>request(`/api/services/${service.id}/runtime`,{startCommand,preDeployCommand,preDeployTimeoutSeconds:preDeployCommand?preDeployTimeout:0,restartPolicy,restartMaxRetries:restartPolicy==='on-failure'?restartRetries:0},'PUT'),'Runtime settings saved. Deploy again to apply.')}}><label htmlFor="runtime-start-command">Start command override</label><input id="runtime-start-command" value={startCommand} onChange={e=>setStartCommand(e.target.value)} maxLength={1024} placeholder="Use the image default"/><label className="spaced-label" htmlFor="pre-deploy-command">Pre-deploy command</label><input id="pre-deploy-command" value={preDeployCommand} onChange={e=>setPreDeployCommand(e.target.value)} maxLength={1024} placeholder="npm run migrate"/>{preDeployCommand&&<><label className="spaced-label" htmlFor="pre-deploy-timeout">Pre-deploy timeout (seconds)</label><input id="pre-deploy-timeout" type="number" min={1} max={3600} value={preDeployTimeout} onChange={e=>setPreDeployTimeout(Number(e.target.value))}/></>} {service.workloadMode!=='cron'&&<div className="form-row spaced-label"><div><label htmlFor="restart-policy">Restart policy</label><select id="restart-policy" value={restartPolicy} onChange={e=>setRestartPolicy(e.target.value)}><option value="on-failure">On failure</option><option value="always">Always</option><option value="never">Never</option></select></div><div><label htmlFor="restart-retries">Maximum retries</label><input id="restart-retries" type="number" min={1} max={100} value={restartRetries} disabled={restartPolicy!=='on-failure'} onChange={e=>setRestartRetries(Number(e.target.value))}/></div></div>}<button className="secondary spaced-label" disabled={busy}>Save runtime settings</button></form></>}
 {!database&&(service.workloadMode==null||service.workloadMode==='web')&&<><h3 className="spaced-label">Primary domain</h3><p className="muted">Point DNS at this server first. Saving replaces the current primary address.</p><form onSubmit={e=>{e.preventDefault();void perform(()=>request(`/api/services/${service.id}/domain`,{host},'PUT'),'Domain saved. Routing will refresh automatically.')}}><label htmlFor="primary-domain">Hostname</label><input id="primary-domain" value={host} onChange={e=>setHost(e.target.value)} required/><button className="secondary spaced-label" disabled={busy}>Save domain</button></form></>}
 {database&&<><h3 className="spaced-label">Connect an application</h3><p className="muted">Save a private connection variable into an application in this environment. Its password stays hidden.</p><label htmlFor="binding-target">Application</label><select id="binding-target" value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose an application</option>{services.filter(s=>s.settings.kind==='http'&&s.projectId===service.projectId&&s.environment===service.environment).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><label htmlFor="binding-variable">Connection variable name</label><input id="binding-variable" value={variable} onChange={e=>setVariable(e.target.value)}/><button className="secondary spaced-label" disabled={!target||busy} onClick={()=>void perform(()=>request(`/api/services/${service.id}/bindings`,{targetServiceId:target,variableName:variable}),'Connection saved. Redeploy the application to apply it.')}>Connect application</button>
 </>}
 {service.settings.volumeName&&<><h3 className="spaced-label">{database?'Database':'Volume'} backups</h3><p className="muted">{onlineBackup?`${postgres?'PostgreSQL':mysql?'MySQL':'MongoDB'} logical backups run while the database is running.`:'Stop this resource before backing up or restoring its volume. Portable volume exports are limited to 1 GB.'}</p><button className="secondary" disabled={busy||pending||!service.activeId||!volumeActionReady} onClick={()=>void perform(()=>request(`/api/services/${service.id}/actions`,{kind:'backup'}),'Backup queued. It will appear below after completion.')}>Create backup</button><div className="backup-list">{backups.filter(b=>b.serviceId===service.id).map(b=><a key={b.id} href={`/api/backups/${b.id}/download`}>{new Date(b.createdAt).toLocaleString()} · {(b.size/1024).toFixed(1)} KB · Download</a>)}</div>
 <h3 className="spaced-label">Restore into an empty {database?'database':'volume'}</h3><p className="muted">The target must be empty. Cloudrail checks first and preserves existing data when restore is rejected.</p><select aria-label="Backup to restore" value={restore} onChange={e=>{setRestore(e.target.value);setConfirm(false)}}><option value="">Choose a backup</option>{backups.filter(b=>{const source=services.find(s=>s.id===b.serviceId);return source?.settings.kind===service.settings.kind&&(!['redis','mysql','mongo'].includes(service.settings.kind)||source.templateVersion===service.templateVersion)}).map(b=><option key={b.id} value={b.id}>{services.find(s=>s.id===b.serviceId)?.name||b.serviceId} · {new Date(b.createdAt).toLocaleString()}</option>)}</select>{confirm?<div className="restore-confirm"><p>Restore the selected backup into {service.name}?</p><button className="secondary" onClick={()=>setConfirm(false)}>Cancel</button><button className="secondary" disabled={busy||pending||!volumeActionReady} onClick={()=>{setConfirm(false);void perform(()=>request(`/api/services/${service.id}/actions`,{kind:'restore',backupId:restore}),'Restore queued. Follow the action status above.')}}>Confirm restore</button></div>:<button className="secondary spaced-label" disabled={!restore||busy||pending||!service.activeId||!volumeActionReady} onClick={()=>setConfirm(true)}>Restore backup</button>}</>}
 {error&&<p className="error-text" role="alert">{error}</p>}{notice&&<p className="success-note" role="status">{notice}</p>}
 </div>
}
