import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { ArrowRight, Layers3, ShieldCheck } from 'lucide-react';

export function OwnerGate({children}:{children:(logout:()=>void)=>ReactNode}){
 const [status,setStatus]=useState<{configured:boolean;email:string}|null>(null);
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [token,setToken]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch('/auth/status',{cache:'no-store'});if(!r.ok)throw new Error('Workspace unavailable');setStatus(await r.json());}catch(e){setError(e instanceof Error?e.message:'Connection failed')}},[]);
 useEffect(()=>{sessionStorage.removeItem('cloudrail-token');void load()},[load]);
 const logout=useCallback(()=>{setStatus(s=>s?{...s,email:''}:s);setPassword('');void load()},[load]);
 if(status?.email)return <>{children(logout)}</>;
 const setup=status&&!status.configured;
 return <div className="login-page"><div className="login-header"><div className="brand"><span className="brand-icon"><Layers3 size={21}/></span>cloudrail</div><span className="preview-tag">YOUR OWN WORKSPACE</span></div><main className="login-card"><div className="eyebrow">YOUR SERVER. YOUR SPACE.</div><h1>{setup?'Make yourself at home.':'Welcome back.'}</h1><p className="login-intro">{setup?'Create the owner account for this Cloudrail installation.':'Sign in to build, deploy and manage your services.'}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(setup?'/auth/setup':'/auth/login',{method:'POST',headers:{'Content-Type':'application/json','X-Cloudrail-Request':'1'},body:JSON.stringify(setup?{email,password,token}:{email,password})});const data=await r.json();if(!r.ok)throw new Error(data.error);setPassword('');setToken('');await load();}catch(e){setError(e instanceof Error?e.message:'Sign-in failed')}finally{setBusy(false)}}}>{setup&&<><label htmlFor="setup-token">Installation setup token</label><input id="setup-token" type="password" value={token} onChange={e=>setToken(e.target.value)} required autoComplete="off"/><p className="field-help">Use CLOUDRAIL_ADMIN_TOKEN from your installation .env file. It works only for initial setup.</p></>}<label htmlFor="owner-email">Email</label><input id="owner-email" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/><label className="spaced-label" htmlFor="owner-password">Password</label><input id="owner-password" type="password" minLength={setup?12:undefined} maxLength={72} autoComplete={setup?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} required/>{setup&&<p className="field-help">Use at least 12 characters.</p>}{error&&<p className="error-text" role="alert">{error}</p>}<button type="submit" className="primary full" disabled={busy||!status}>{busy?'Please wait…':setup?'Create workspace':'Sign in'}<ArrowRight size={16}/></button></form><p className="login-help"><ShieldCheck size={15}/>Your session stays in an HttpOnly cookie.</p>{!status&&error&&<button className="secondary full" onClick={()=>void load()}>Retry connection</button>}</main><footer className="login-footer">Open source. On your terms.<span>Cloudrail</span></footer></div>
}
