import { useEffect, useState } from 'react';
import { KeyRound, Plus, Trash2, Play, Square, RotateCw, ShieldCheck, Clock3 } from 'lucide-react';
type Request=<T>(path:string,body?:unknown,method?:string)=>Promise<T>;
export function VariablesPanel({serviceID,request}:{serviceID:string;request:Request}){
 const [names,setNames]=useState<string[]>([]);const [name,setName]=useState('');const [value,setValue]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const load=async()=>{const data=await request<{names:string[]}>(`/api/services/${serviceID}/variables`);setNames(data.names)};
 useEffect(()=>{void load().catch(e=>setError(e.message))},[serviceID,request]);
 return <div className="deployment-content"><div className="settings-intro"><KeyRound size={20}/><h3>Runtime variables</h3><p>Values are encrypted and hidden after saving. Changes apply to the next deployment.</p></div><div className="variable-list">{names.length===0&&<p className="muted">No variables yet.</p>}{names.map(n=><div key={n}><code>{n}</code><span>••••••••</span><button className="icon-button" aria-label={`Delete ${n}`} disabled={busy} onClick={async()=>{setBusy(true);try{await request(`/api/services/${serviceID}/variables/${encodeURIComponent(n)}`,undefined,'DELETE');await load();setNotice('Variable deleted. Deploy again to apply.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Trash2 size={14}/></button></div>)}</div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await request(`/api/services/${serviceID}/variables/${encodeURIComponent(name)}`,{value},'PUT');setName('');setValue('');await load();setNotice('Saved securely. Deploy again to apply.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label htmlFor="var-name">Variable name</label><input id="var-name" value={name} onChange={e=>setName(e.target.value)} placeholder="DATABASE_URL" pattern="[A-Za-z_][A-Za-z0-9_]*" required maxLength={128}/><label className="spaced-label" htmlFor="var-value">New value</label><input id="var-value" type="password" autoComplete="off" value={value} onChange={e=>setValue(e.target.value)} maxLength={8192}/><button className="primary spaced-label" disabled={busy}><Plus size={14}/>{names.includes(name)?'Replace value':'Save variable'}</button></form>{error&&<p role="alert" className="error-text">{error}</p>}{notice&&<p role="status" className="success-note">{notice}</p>}</div>
}
type CronRun={id:string;serviceId:string;deploymentId:string;scheduledFor:string;status:string;exitCode?:number;logs:string;error:string;startedAt?:string;finishedAt?:string};
export function SettingsPanel({service,actions,cronRuns,request,refresh}:{service:{id:string;activeId:string;desiredState:string;environment:string;workloadMode:string;cronSchedule:string;cronNextRun?:string},actions:{id:string;kind:string;status:string;error:string}[],cronRuns:CronRun[],request:Request;refresh:()=>Promise<unknown>}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [schedule,setSchedule]=useState(service.cronSchedule||'');const pending=actions.some(a=>a.status==='queued'||a.status==='running');
 useEffect(()=>setSchedule(service.cronSchedule||''),[service.id,service.cronSchedule]);
 const action=async(kind:string)=>{setBusy(true);setError('');try{await request(`/api/services/${service.id}/actions`,{kind});await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const saveCron=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{await request(`/api/services/${service.id}/cron`,{schedule},'PUT');await refresh();setNotice('UTC schedule saved. Deploy a release to activate runs.')}catch(err){setError((err as Error).message)}finally{setBusy(false)}};
 return <div className="deployment-content"><div className="settings-intro"><ShieldCheck size={20}/><h3>Service controls</h3><p>Actions affect this service in {service.environment} only. Configuration and deployment history are retained.</p></div>{service.workloadMode==='cron'&&<><h3 className="spaced-label"><Clock3 size={14}/> UTC schedule</h3><p className="muted">Five fields: minute, hour, day of month, month and day of week. Missed intervals are coalesced into one run.</p><form onSubmit={saveCron}><label htmlFor="cron-schedule">Cron expression</label><input id="cron-schedule" value={schedule} onChange={e=>setSchedule(e.target.value)} required maxLength={100} placeholder="*/15 * * * *"/><button className="secondary spaced-label" disabled={busy}>Save schedule</button></form><div className="control-state">Next run <strong>{service.cronNextRun?new Date(service.cronNextRun).toLocaleString():'Save a schedule first'}</strong></div><h3 className="spaced-label">Run history</h3><div className="action-history cron-history">{cronRuns.slice(0,20).map(run=><div key={run.id}><span>{new Date(run.scheduledFor).toLocaleString()}</span><strong className={`resource-status ${run.status}`}>{run.status}{run.exitCode!=null?` · exit ${run.exitCode}`:''}</strong>{run.error&&<p>{run.error}</p>}{run.logs&&<pre>{run.logs}</pre>}</div>)}{!cronRuns.length&&<p className="muted">No scheduled runs yet.</p>}</div></>}<div className="control-state">Desired state <strong>{service.desiredState}</strong></div><div className="service-actions"><button className="secondary" disabled={busy||pending||!service.activeId} onClick={()=>void action('start')}><Play size={14}/>Start</button><button className="secondary" disabled={busy||pending||!service.activeId} onClick={()=>void action('restart')}><RotateCw size={14}/>Restart</button><button className="secondary" disabled={busy||pending||!service.activeId} onClick={()=>void action('stop')}><Square size={14}/>Stop</button></div>{error&&<p role="alert" className="error-text">{error}</p>}{notice&&<p role="status" className="success-note">{notice}</p>}<h3 className="spaced-label">Recent actions</h3><div className="action-history">{actions.slice(0,10).map(a=><div key={a.id}><span>{a.kind}</span><strong>{a.status}</strong>{a.error&&<p>{a.error}</p>}</div>)}{!actions.length&&<p className="muted">No actions yet.</p>}</div></div>
}
