import {useEffect,useRef,useState} from 'react';
type Request=<T>(path:string,body?:unknown,method?:string)=>Promise<T>;
type Source={repository:string;installation:number;branch:string;root:string;builder:string;dockerfile:string;buildCommand:string;startCommand:string;port:number;healthPath:string;autoDeploy:boolean};
type Build={id:string;commit:string;status:string;logs:string;error:string;image:string;deploymentId:string;createdAt:string};
const initial:Source={repository:'',installation:0,branch:'main',root:'',builder:'dockerfile',dockerfile:'Dockerfile',buildCommand:'',startCommand:'',port:3000,healthPath:'/',autoDeploy:false};
export function SourcePanel({serviceID,request}:{serviceID:string;request:Request}){
 const [source,setSource]=useState<Source>(initial);const [builds,setBuilds]=useState<Build[]>([]);const [selected,setSelected]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);const [configured,setConfigured]=useState(false);
 const [installations,setInstallations]=useState<{id:number;account:{login:string}}[]>([]);const [repos,setRepos]=useState<{full_name:string;default_branch:string}[]>([]);const [branches,setBranches]=useState<{name:string}[]>([]);const key=useRef(crypto.randomUUID());
 const update=<K extends keyof Source>(name:K,value:Source[K])=>{setSource(s=>({...s,[name]:value}));setSaved(false);setNotice('')};
 useEffect(()=>{let stopped=false;void Promise.all([request<{source:Source|null}>(`/api/services/${serviceID}/source`),request<{configured:boolean}>('/api/github')]).then(([v,g])=>{if(!stopped){if(v.source){setSource(v.source);setSaved(true)}setConfigured(g.configured)}}).catch(e=>setError(e.message));const poll=async()=>{try{const data=await request<Build[]>(`/api/services/${serviceID}/builds`);if(!stopped)setBuilds(data)}catch(e){if(!stopped)setError((e as Error).message)}};void poll();const timer=setInterval(poll,2000);return()=>{stopped=true;clearInterval(timer)}},[serviceID,request]);
 const build=builds.find(b=>b.id===selected)||builds[0];
 return <div className="deployment-content source-panel"><h3>Deploy from GitHub</h3><p className="muted">Choose a repository and branch. Each build records the exact commit it uses.</p>{configured&&<button className="secondary" onClick={async()=>{try{setInstallations(await request('/api/github/installations'))}catch(e){setError((e as Error).message)}}}>Load GitHub installations</button>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await request(`/api/services/${serviceID}/source`,source,'PUT');setSaved(true);setNotice('Source saved. Ready to build.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
 <label htmlFor="source-installation">Repository access</label><select id="source-installation" value={source.installation} onChange={async e=>{const id=Number(e.target.value);update('installation',id);setRepos([]);if(id)try{const data=await request<{repositories:{full_name:string;default_branch:string}[]}>(`/api/github/repositories?installation=${id}`);setRepos(data.repositories)}catch(e){setError((e as Error).message)}}}><option value={0}>Public repository</option>{source.installation>0&&!installations.some(i=>i.id===source.installation)&&<option value={source.installation}>Installation {source.installation}</option>}{installations.map(i=><option key={i.id} value={i.id}>{i.account.login}</option>)}</select>
 <label htmlFor="source-repo">Repository</label><input id="source-repo" list="repository-options" placeholder="owner/repository" required value={source.repository} onChange={e=>{update('repository',e.target.value);const r=repos.find(r=>r.full_name===e.target.value);if(r)update('branch',r.default_branch)}}/><datalist id="repository-options">{repos.map(r=><option key={r.full_name} value={r.full_name}/>)}</datalist><button type="button" className="text-button" onClick={async()=>{try{setBranches(await request(`/api/github/branches?installation=${source.installation}&repository=${encodeURIComponent(source.repository)}`))}catch(e){setError((e as Error).message)}}}>Load branches</button>
 <label htmlFor="source-branch">Branch</label><input id="source-branch" list="branch-options" value={source.branch} onChange={e=>update('branch',e.target.value)} required/><datalist id="branch-options">{branches.map(b=><option key={b.name} value={b.name}/>)}</datalist>
 <label htmlFor="source-root">Root directory</label><input id="source-root" value={source.root} placeholder="Repository root" onChange={e=>update('root',e.target.value)}/>
 <label htmlFor="source-builder">Build method</label><select id="source-builder" value={source.builder} onChange={e=>update('builder',e.target.value)}><option value="dockerfile">Dockerfile</option><option value="railpack">Railpack — detect application</option></select>
 {source.builder==='dockerfile'?<><label htmlFor="source-dockerfile">Dockerfile path</label><input id="source-dockerfile" value={source.dockerfile} onChange={e=>update('dockerfile',e.target.value)}/></>:<><label htmlFor="build-command">Build command override</label><input id="build-command" value={source.buildCommand} onChange={e=>update('buildCommand',e.target.value)} placeholder="Detect automatically"/><label htmlFor="start-command">Start command override</label><input id="start-command" value={source.startCommand} onChange={e=>update('startCommand',e.target.value)} placeholder="Detect automatically"/></>}
 <div className="form-row"><div><label htmlFor="source-port">Application port</label><input id="source-port" type="number" min={1} max={65535} value={source.port} onChange={e=>update('port',Number(e.target.value))}/></div><div><label htmlFor="source-health">Readiness path</label><input id="source-health" value={source.healthPath} onChange={e=>update('healthPath',e.target.value)}/></div></div>
 <label className="checkbox-label"><input type="checkbox" disabled={!source.installation} checked={source.autoDeploy} onChange={e=>update('autoDeploy',e.target.checked)}/>Deploy pushes to this branch</label>{!source.installation&&<p className="field-help">Connect a GitHub App installation to enable push deployments.</p>}
 <button className="secondary" disabled={busy}>{busy?'Saving…':'Save source'}</button></form>
 <button className="primary spaced-label" disabled={busy||!saved} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch(`/api/services/${serviceID}/builds`,{method:'POST',headers:{'Content-Type':'application/json','X-Cloudrail-Request':'1','Idempotency-Key':key.current},body:'{}'});const b=await r.json();if(!r.ok)throw new Error(b.error);key.current=crypto.randomUUID();setSelected(b.id);setBuilds(items=>[b,...items]);setNotice('Build queued. Logs will appear below.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Build & deploy</button>
 {notice&&<p className="success-note" role="status">{notice}</p>}{error&&<p className="error-text" role="alert">{error}</p>}
 <h3 className="spaced-label">Build history</h3>{!build&&<p className="muted">No builds yet.</p>}{build&&<><select aria-label="Build history" value={build.id} onChange={e=>setSelected(e.target.value)}>{builds.map(b=><option key={b.id} value={b.id}>{b.commit.slice(0,8)} · {b.status} · {new Date(b.createdAt).toLocaleString()}</option>)}</select><p className="build-status">{build.status}{build.deploymentId?' · deployment queued':''}</p>{(build.status==='queued'||build.status==='building')&&<button className="secondary" onClick={async()=>{try{await request(`/api/builds/${build.id}/cancel`,{})}catch(e){setError((e as Error).message)}}}>Cancel build</button>}{build.error&&<p className="error-text">{build.error}</p>}<pre className="build-logs">{build.logs||'Waiting for build output…'}</pre>{build.image&&<p className="build-digest">{build.image}</p>}</>}
 </div>
}
export function GitHubSettings({request,close}:{request:Request;close:()=>void}){
 const modalRef=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;modalRef.current?.querySelector<HTMLInputElement>('input')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const items=[...(modalRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),a[href]')||[])];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[]);
 const [appId,setID]=useState('');const [slug,setSlug]=useState('');const [privateKey,setKey]=useState('');const [webhookSecret,setSecret]=useState('');const [configured,setConfigured]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{void request<{configured:boolean;appId:string;slug:string}>('/api/github').then(v=>{setID(v.appId);setSlug(v.slug);setConfigured(v.configured)}).catch(e=>setError(e.message))},[request]);
 return <div className="modal-shade"><section ref={modalRef} className="modal" role="dialog" aria-modal="true" aria-labelledby="github-title"><button className="icon-button close-modal" onClick={close} aria-label="Close GitHub settings">×</button><h2 id="github-title">Connect GitHub</h2><p className="muted">Use a GitHub App with read access to Contents and Metadata, subscribed to push events.</p><p className="field-help">Webhook URL: {location.origin}/webhooks/github</p>{configured&&<p className="success-note">App configured. Credentials stay hidden.</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await request('/api/github',{appId,slug,privateKey,webhookSecret},'PUT');setKey('');setSecret('');setConfigured(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label htmlFor="app-id">App ID</label><input id="app-id" value={appId} required onChange={e=>setID(e.target.value)}/><label htmlFor="app-slug">App slug</label><input id="app-slug" value={slug} required onChange={e=>setSlug(e.target.value)}/><label htmlFor="app-key">Private key (.pem)</label><input id="app-key" type="file" accept=".pem" onChange={async e=>{const f=e.target.files?.[0];if(f&&f.size<20000)setKey(await f.text());else setError('Choose a PEM file under 20 KB')}}/><label htmlFor="app-secret">Webhook secret</label><input id="app-secret" type="password" minLength={32} value={webhookSecret} onChange={e=>setSecret(e.target.value)} required autoComplete="off"/><button className="primary spaced-label" disabled={busy||!privateKey}>{busy?'Saving…':'Save connection'}</button></form>{configured&&<a className="secondary install-link" target="_blank" rel="noreferrer" href={`https://github.com/apps/${encodeURIComponent(slug)}/installations/new`}>Install app on GitHub ↗</a>}{error&&<p role="alert" className="error-text">{error}</p>}</section></div>
}
