import {test,expect} from '@playwright/test';
import {randomBytes} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

test('first owner registers without a token, then signs out and signs in on mobile',async({page})=>{
 const status=await (await page.request.get('/auth/status')).json();
 test.skip(status.configured,'Requires a fresh installation; never replaces an existing owner.');
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const screenshots=fileURLToPath(new URL('../../../.data/screenshots/',import.meta.url));
 mkdirSync(screenshots,{recursive:true});
 const owner={email:'owner@cloudrail.local',password:randomBytes(24).toString('base64url')};
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'Create your account',exact:true})).toBeVisible();
 await expect(page.getByLabel(/token/i)).toHaveCount(0);
 await page.screenshot({path:screenshots+'owner-setup.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.screenshot({path:screenshots+'owner-setup-mobile.png',fullPage:true});
 await page.getByLabel('Email',{exact:true}).fill(owner.email);
 await page.getByLabel('Password',{exact:true}).fill(owner.password);
 await page.getByLabel('Confirm password',{exact:true}).fill('does-not-match');
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await expect(page.getByRole('alert')).toHaveText('Passwords do not match');
 await page.getByRole('button',{name:'Show password',exact:true}).click();
 await expect(page.getByLabel('Password',{exact:true})).toHaveAttribute('type','text');
 await page.getByRole('button',{name:'Hide password',exact:true}).click();
 await page.getByLabel('Confirm password',{exact:true}).fill(owner.password);
 // Private fixture for subsequent acceptance tests; never checked into source control.
 writeFileSync(new URL('../../../.data/test-owner.json',import.meta.url),JSON.stringify(owner),{mode:0o600});
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await expect(page.getByRole('button',{name:'Sign out',exact:true}).filter({visible:true})).toBeVisible();
 const cookies=await page.context().cookies();
 expect(cookies.find(c=>c.name==='cloudrail_session')).toMatchObject({httpOnly:true,sameSite:'Strict'});
 await page.getByRole('button',{name:'Sign out',exact:true}).filter({visible:true}).click();
 await expect(page.getByRole('heading',{name:'Welcome back.'})).toBeVisible();
 await expect(page.getByLabel('Confirm password',{exact:true})).toHaveCount(0);
 await page.getByLabel('Password',{exact:true}).fill('wrong-password');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByRole('alert')).toHaveText('Email or password is incorrect');
 await page.getByLabel('Password',{exact:true}).fill(owner.password);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByRole('button',{name:'Sign out',exact:true}).filter({visible:true})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('button',{name:'Sign out',exact:true}).filter({visible:true})).toBeVisible();
 expect(errors).toEqual([]);
});
