import { test, expect } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const screenshots = fileURLToPath(new URL('../../../.data/screenshots/', import.meta.url));
mkdirSync(screenshots, { recursive: true });

test('real dashboard: create, validate, deploy, inspect logs, recover, and use mobile layout', async ({ page }) => {
  const image = JSON.parse(execFileSync('docker', ['image', 'inspect', 'traefik/whoami:v1.11.0', '--format', '{{json .RepoDigests}}'], { encoding: 'utf8' }))[0];
  const owner = JSON.parse(readFileSync(new URL('../../../.data/test-owner.json', import.meta.url), 'utf8'));
  const errors: string[] = [];
  page.on('pageerror', err => errors.push(err.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await page.screenshot({ path: screenshots + 'login.png', fullPage: true });
  await page.getByLabel('Email', {exact:true}).fill(owner.email);
  await page.getByLabel('Password', {exact:true}).fill(owner.password);
  await page.getByRole('button', { name: 'Sign in', exact:true }).click();
  await expect(page.getByText('Control plane connected')).toBeVisible();
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  let dialog = page.getByRole('dialog');
  const project = 'Browser demo ' + Date.now().toString().slice(-6);
  await dialog.getByLabel('Project name').fill(project);
  await dialog.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page.getByRole('heading', { name: project, exact: true })).toBeVisible();
  await page.getByLabel('Create environment', {exact:true}).click();
  await page.getByRole('dialog').getByLabel('Environment name').fill('staging');
  await page.getByRole('dialog').getByRole('button', {name:'Create environment',exact:true}).click();
  await expect(page.getByLabel('Environment', {exact:true})).toHaveValue('staging');
  await page.getByRole('button', { name: 'New resource', exact: true }).click();
  await page.getByRole('dialog', {name:'Add to your canvas'}).getByRole('button', {name:/Empty Service/}).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Resource name').fill('hello-api');
  await dialog.getByRole('button', { name: 'Create resource' }).click();
  await expect(page.getByRole('region', { name: 'hello-api details' })).toBeVisible();
  await page.getByRole('tab', {name:'Variables',exact:true}).click();
  await page.getByLabel('Variable name').fill('DEMO_VALUE');
	await page.getByLabel('Secret value').fill('browser-secret-value');
  await page.getByRole('button', {name:'Save variable'}).click();
	await expect(page.getByText('Secret saved. Deploy again to apply.')).toBeVisible();
	await expect(page.getByLabel('Secret value')).toHaveValue('');
  await page.getByRole('tab', {name:/^Deployments/}).click();
  await page.getByRole('button', { name: 'Deploy', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Container image').fill('nginx:latest');
  await dialog.getByRole('button', { name: 'Deploy image', exact: true }).click();
  await expect(dialog.getByRole('alert')).toContainText('pinned by digest');
  await dialog.getByLabel('Container image').fill(image);
  await dialog.getByRole('button', { name: 'Deploy image', exact: true }).click();
  await expect(page.locator('.release-card.active')).toBeVisible({ timeout: 45000 });
  const appURL = await page.locator('.service-address a').getAttribute('href');
  const app = await page.context().newPage();
  await app.goto(appURL!);
  await expect(app.locator('body')).toContainText('Hostname:');
  await app.close();
  await page.screenshot({ path: screenshots + 'dashboard.png', fullPage: true });
  await page.getByRole('tab', { name: 'Runtime logs' }).click();
  await expect(page.locator('.logs-view pre')).toContainText('Starting up');
  await page.getByRole('tab', { name: 'Deployments' }).click();
  await page.getByRole('button', { name: 'Deploy', exact: true }).click();
  dialog = page.getByRole('dialog');
  await dialog.getByLabel('Container image').fill(image);
  await dialog.getByLabel('Container port').fill('1');
  await dialog.getByRole('button', { name: 'Deploy image', exact: true }).click();
  await expect(page.locator('.release-card.failed')).toBeVisible({ timeout: 45000 });
  await expect(page.getByText('Previous release is still selected for traffic.')).toBeVisible();
  await page.screenshot({ path: screenshots + 'failed-deployment.png', fullPage: true });
  const result = await page.request.get(appURL!);
  expect(result.ok()).toBeTruthy();
  await page.getByLabel('Filter resources').fill('does-not-exist');
  await expect(page.getByText('No resources match')).toBeVisible();
  await page.getByLabel('Filter resources').fill('');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: screenshots + 'mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.getByRole('button', { name: 'Deploy', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('tab', {name:'Settings',exact:true}).click();
  await page.getByRole('button', {name:'Stop',exact:true}).click();
  await expect(page.locator('.control-state')).toContainText('stopped',{timeout:20000});
  await page.getByRole('button', {name:'Start',exact:true}).click();
  await expect(page.locator('.control-state')).toContainText('running',{timeout:20000});
  await page.screenshot({path:screenshots+'service-settings.png',fullPage:true});
  expect(errors).toEqual([]);
});
